server.port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note_pad
    username: your-database-user-name
    password: your-database-password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
